sonar.organization=alejomon
sonar.projectKey=DavidAlejo24_Wakka-Tattoes
sonar.host.url=https://sonarcloud.io

# Ruta a los archivos que quieres analizar (el punto es la carpeta actual)
sonar.sources=.

# Opcional: codificación de los archivos
sonar.sourceEncoding=UTF-8
sonar.token=fb2f96b402d9e6db9ee160f3d2bdaafba89bdbde